### ISSUE TITLE
geval is not working?

### ISSUE THREAD

**Issue by djstrong** [poleval/2021-punctuation-restoration#1]
```
2021-punctuation-restoration$ cp train/expected.tsv train/out.tsv 
2021-punctuation-restoration$ geval -t train/
geval: src/GEval/Metric.hs:(101,3)-(168,143): Non-exhaustive patterns in function readsPrec
```

**Comment by djstrong** [comment]
To pewnie przez starą binarkę pod https://gonito.net/get/bin/geval

**Comment by djstrong** [comment]
Z przekompilowanym geval:
`geval: Line 71: Unexpected data [endOfInput]`

**Comment by filipggg** [comment]
Dziękuję za znalezienie problemu.

1. Rzeczywiście trzeba użyć najnowszego gevala z https://gonito.net/get/bin/geval
2. Poprawiłem też błąd w konfiguracji, teraz powinno być OK.

**Comment by djstrong** [comment]
Dalej mam błąd `geval: Line 71: Unexpected data [endOfInput]`

**Comment by djstrong** [comment]
Już się domyśliłem - poprawiona konfiguracja jest w innej gałęzi ;)

**Comment by filipggg** [comment]
Zakładam, że wszystko jest OK, więc zamykam.
